name: CI

on:
    pull_request:
        branches: [main]

jobs:
    build:
        name: Test Build and Run Dev For Kanban Reporter
        timeout-minutes: 15
        runs-on: ubuntu-latest

        steps:
          - name: Call kanban-reporter-dev
            uses: ./.github/workflows/kanban-reporter-dev.yml
            