name: send-kanban-reporter-dev

on:
  workflow_call:
    secrets:
      config_properties_dev:
        required: true
      filter_json_dev:
        required: true

jobs:
  build:
    name: Run Dev For Kanban Reporter
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
            java-version: '22'
            distribution: 'adopt'

      - name: Set Permissions For Gradlew
        run: chmod +x ./kanban-reporter/gradlew

      - name: Clean Build
        run: |
            cd kanban-reporter
            ./gradlew clean

      - name: Setup config.properties (dev)
        run: |
            cd kanban-reporter
            mkdir -p ./app/src/main/resources/dev
            cat << EOF > ./app/src/main/resources/dev/config.properties
            ${{ secrets.config_properties_dev }}
            EOF

      - name: Setup filter.json (dev)
        run: |
            cd kanban-reporter
            mkdir -p ./app/src/main/resources/dev
            cat << EOF > ./app/src/main/resources/dev/filter.json
            ${{ secrets.filter_json_dev }}
            EOF

      - name: Refresh Dependencies
        run: |
            cd kanban-reporter
            ./gradlew --refresh-dependencies
        
      - name: Build Test
        run: |
            cd kanban-reporter
            ./gradlew build
        
      - name: Run Dev
        run: |
            cd kanban-reporter
            env=dev ./gradlew run
